### ISSUE TITLE
Beta task checklist

### ISSUE THREAD

**Issue by dreamwhisper** [studiopress/pattern-manager#57]
- [ ] Add error message if post type added to pattern no longer exists. eg. _A post type added to your pattern no longer exists._ / _You have a post type in your pattern that doesn't exist in WordPress._
- [x] Renaming a pattern creates a new copy. https://github.com/studiopress/pattern-manager/pull/61
- [x] consider doing a couple of things when a theme is changed:
      - Delete all pm_pattern posts (these are not needed as we pull from files) https://github.com/studiopress/pattern-manager/pull/62
      - Send a notice through the heartbeat API to any patterns still open that says _The theme was changed. This pattern does not exist in this theme. Please close this tab._ https://github.com/studiopress/pattern-manager/pull/65
- [x] Make sure child themes work https://github.com/studiopress/pattern-manager/pull/69/
- [x] Make sure content isn't stale when using back button.
- [x] Ensure assets save appropriately. (related to tree-shaking, which is removed now) https://github.com/studiopress/pattern-manager/pull/91
- [x] Deleting title on the edit screen, then saving results in a php error https://github.com/studiopress/pattern-manager/pull/67
- [x] Ensure error messages are read by screen readers. [wp.a11y.speak](https://make.wordpress.org/accessibility/handbook/markup/wp-a11y-speak/)
- [x] Make sure the previews resize with a browser resize. #109 
- [x] Wide alignment not working in pattern editor in 6.2 beta.
- [ ] Default width from theme.json not working.

Feel free to edit as needed. We could also create a project if we feel it is needed.
